name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push
env:
  TZ: Asia/Shanghai
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: testFunc
      run: |
        # 把需要的变量输出到系统的ENV中    
        # 得到当前git库更新的时间
        gitCommitIime=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        gitCommit_seconds=$(date --date="${gitCommitIime}" +%s)
        now_seconds=$(date +%s)
        echo "SECONDS_FROM_LAST__COMMIT="$((now_seconds-gitCommit_seconds))"" >> $GITHUB_ENV
      if: ${{env.SECONDS_FROM_LAST__COMMIT >= 300}}
    - name: echo some
        echo "hello world"
      
      
