name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: testFunc
      run: |
        ssss="SECONDS_FROM_LAST__COMMIT="$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")"" #>> $GITHUB_ENV
        echo ${ssss}
    - name: echo some
      #if: ${{env.SECONDS_FROM_LAST__COMMIT <= 300}}
      run: |
        echo "hello world"
      
      
