name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push
env:
  TZ: Asia/Shanghai
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: testFunc
      run: |
        echo "REPORT_DATE=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo (${{env.REPORT_DATE}})
        echo ${{env.REPORT_DATE}}
    - name: echo some
      run: |
        echo "hello world"
      
      
