name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: testFunc
      run: |
        gitCommitIime=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        gitCommit_seconds=$(date --date="${gitCommitIime}" +%s)
        now_seconds=$(date +%s)
        echo "SECONDS_FROM_LAST__COMMIT="$((now_seconds-gitCommit_seconds))"" >> $GITHUB_ENV
        echo ${{evn.SECONDS_FROM_LAST__COMMIT}} "2561dsasdas"
    - name: echo some
      if: ${{env.SECONDS_FROM_LAST__COMMIT >= 300}}
      run: |
        echo "hello world"
      
      
