name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push

#env:
#  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Compare GitCommitIimeGithub And GitCommitIimeGitee
      run: |
        now_seconds=$(date +%s)
        gitCommitIimeGithub=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGithub='${gitCommitIimeGithub}        
        gitHUBCommit_seconds=$(date --date="${gitCommitIimeGithub}" +%s)   
        echo 'gitHUBCommit_seconds='${gitHUBCommit_seconds}
        secondsFromLastCommit_GITHUB="$((now_seconds-gitHUBCommit_seconds))"
        echo 'secondsFromLastCommit_GITHUB='${secondsFromLastCommit_GITHUB}        
        mkdir tempCloneDir
        cd ./tempCloneDir/
        git clone  https://gitee.com/skyskin-w/Test.git #gitee仓库地址
        cd ./Test/
        gitCommitIimeGitee=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGitee='${gitCommitIimeGitee}
        gitEECommit_seconds=$(date --date="${gitCommitIimeGitee}" +%s)
        echo 'gitEECommit_seconds='${gitEECommit_seconds}
        secondsFromLastCommit_GITEE="$((now_seconds-gitEECommit_seconds))"
        echo 'secondsFromLastCommit_GITEE='${secondsFromLastCommit_GITEE}        
        GITHUB_GITEE="$((gitHUBCommit_seconds-gitEECommit_seconds))"
        CompareTimeResult="${GITHUB_GITEE}"
        echo 'CompareTimeResult=${CompareTimeResult}'
