name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: testFunc
      run: |
        gitCommitIime=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        gitCommit_seconds=$(date --date="${gitCommitIime}" +%s)
        now_seconds=$(date +%s)
        secondsFromLastCommit="$((now_seconds-gitCommit_seconds))"
        echo "SECONDS_FROM_LAST__COMMIT="$((now_seconds-gitCommit_seconds))"" >> $GITHUB_ENV
        echo 'secondsFromLastCommit='${secondsFromLastCommit}
    - name: echo some 10
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 10}}
      run: |
        echo "hello world 10"
    - name: echo some 11
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 11}}
      run: |
        echo "hello world 11"
    - name: echo some 12
      if: ${{env.SECONDS_FROM_LAST__COMMIT <= 12}}
      run: |
        echo "hello world 12"
    - name: echo some 13
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 13}}
      run: |
        echo "hello world 13"
    - name: echo some 14
      if: ${{env.SECONDS_FROM_LAST__COMMIT <= 14}}
      run: |
        echo "hello world 14"   
    - name: echo some 15
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 15}}
      run: |
        echo "hello world 15"                                
    - name: echo some 16
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 16}}
      run: |
        echo "hello world 16"
    - name: echo some 17
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 17}}
      run: |
        echo "hello world 17"   
    - name: echo some 18
      if: ${{env.SECONDS_FROM_LAST__COMMIT == 18}}
      run: |
        echo "hello world 18"     
      
