name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push

#env:
#  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Compare GitCommitIimeGithub And gitCommitIimeGitee
      run: |
        ls
        gitCommitIimeGithub=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        mkdir tempCloneDir
        cd ./tempCloneDir/
        git clone  https://gitee.com/skyskin-w/Test.git #gitee仓库地址
        cd ./Test
        gitCommitIimeGitee=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGithub='${gitCommitIimeGithub}
        echo 'gitCommitIimeGitee='${gitCommitIimeGitee}
        if [ "$((gitCommitIimeGithub==gitCommitIimeGitee))" -eq "1" ]; then
            echo "AUTO_PAKEGE=1 >> $GITHUB_ENV
        fi
