name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push

#env:
#  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Compare GitCommitIimeGithub And GitCommitIimeGitee
      run: |
        ls
        gitCommitIimeGithub=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGitHUB='${gitCommitIimeGithub}        
        gitHUBCommit_seconds=$(date --date="${gitCommitIimeGitHUB}" +%s)   
        echo 'gitHUBCommit_seconds='${gitHUBCommit_seconds}
        mkdir tempCloneDir
        cd ./tempCloneDir/
        git clone  https://gitee.com/skyskin-w/Test.git #gitee仓库地址
        cd ./Test/
        gitCommitIimeGitee=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGitEE='${gitCommitIimeGitee}
        gitEECommit_seconds=$(date --date="${gitCommitIimeGitEE}" +%s)
        echo 'gitEECommit_seconds='${gitEECommit_seconds}
        GITHUB_GITEE="$((gitHUBCommit_seconds-gitEECommit_seconds))"
        CompareTimeResult="${GITHUB_GITEE}"
        echo 'CompareTimeResult=${CompareTimeResult}'
