name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: push

#env:
#  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Compare GitCommitIimeGithub And GitCommitIimeGitee
      run: |
        #得到github项目对应的最后提交时间
        gitCommitIimeGithub=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGithub='${gitCommitIimeGithub}       

        #得到github项目对应的最后提交时间秒数
        gitHUBCommit_seconds=$(date --date="${gitCommitIimeGithub}" +%s)   
        echo 'gitHUBCommit_seconds='${gitHUBCommit_seconds}

        #创建临时文件拉取gitee
        mkdir tempCloneDir
        cd ./tempCloneDir/
        git clone  https://gitee.com/skyskin-w/Test.git #gitee仓库地址
        cd ./Test/

        #得到gitee项目对应的最后提交时间
        gitCommitIimeGitee=$(date --date="$(git show --pretty=format:"%ci" | head -1)" "+%Y-%m-%d %H:%M:%S")
        echo 'gitCommitIimeGitee='${gitCommitIimeGitee}

        #得到gitee项目对应的最后提交时间秒数
        gitEECommit_seconds=$(date --date="${gitCommitIimeGitee}" +%s)
        echo 'gitEECommit_seconds='${gitEECommit_seconds}
      
        #得到 (github提交时间 -  gitee提交时间)
        GITHUB_GITEE="$((gitHUBCommit_seconds-gitEECommit_seconds))"
        echo 'GITHUB_GITEE=${GITHUB_GITEE}'

        


